## Arrays

In [1]:
import numpy

def arrays(arr):
    return numpy.array(arr, float)[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

In [2]:
import numpy as np
a=np.array(list(map(int,input().split())))
a.shape=(3,3)
print(a)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [3]:
import numpy as np

n, m = map(int, input().split())
array = np.array([input().strip().split() for _ in range(n)], int)
print(array.transpose())
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [4]:
import numpy

n,m,p=map(int,input().split())

lista1=[list(map(int,input().split())) for i in range(n)]
lista2=[list(map(int,input().split())) for i in range(m)]
a1=numpy.array(lista1)
a2=numpy.array(lista2)

print(numpy.concatenate((a1,a2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
 3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [5]:
import numpy as np
shape= tuple(map(int,input().split()))
print(np.zeros(shape,int), np.ones(shape,int), sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [7]:
import numpy
print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics

In [8]:
import numpy

n, m = [int(x) for x in input().strip().split()]

a = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])
b = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])

print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [9]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [10]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24


## Min and Max

In [11]:
import numpy
arr=[]
n,m= map(int,input().split())
for row in range(n):
    my_arr=list(map(int,input().split()))
    arr.append(my_arr)
my_array=numpy.array(arr)
result=numpy.min(my_array, axis = 1)
print(max(result))

4 5
2 5
3 7
1 3
4 0
3


## Mean, Var, and Std

In [12]:
import numpy

nm = input().split()
n = int(nm[0])
m = int(nm[1])
arr = []
for i in range(n):
    m = list(map(int, input().split()))
    arr.append(m)
arr = numpy.array(arr)

mean = numpy.mean(arr, axis = 1)
var = numpy.var(arr, axis = 0)
std = numpy.std(arr)

print(mean)
print(var)

rnd = numpy.around(std, 11)
print(rnd)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Dot and Cross

In [13]:
import numpy as np

n = int(input())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(np.dot(a, b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer

In [15]:
import numpy as np

arr1 = np.array(list(map(int, input().strip().split())))
arr2 = np.array(list(map(int, input().strip().split())))

print(np.inner(arr1, arr2))
print(np.outer(arr1, arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials

In [16]:
import numpy

poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

1.1 2 3
0
3.0


## Linear Algebra

In [17]:
import numpy
n=int(input())
a=numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(legacy='1.13') 
print(numpy.linalg.det(a))

2
1.1 1.1
1.1 1.1
0.0
